### ISSUE TITLE
Question RE Login page

### ISSUE THREAD

**Issue by jordc73** [Gubbinz117/Pentana-PowerBI-Connectors#1]
Hello,

I've set this up for a colleague recently and we are unsure of what should be entered in the "Client_secret" box under the username & Password box. After some googling I am finding that some applications have a client secret - would that be the case? 

Or is this client secret specific to the user? 

Thanks

**Comment by Gubbinz117** [comment]
It's the client secret generated when you set up the api access. If you are unsure how to generate this Pentana have some documentation on it.

**Comment by jordc73** [comment]
Thank you for getting back to me so soon, appreciate it
